Repository Arquisoft/dede_es3a, pull requests merged in 2022-03, with the labels that each got.

#82 prototipos añadidos
  docs/bocetos_interfez/a_prototipo_carrito.png
  docs/bocetos_interfez/a_prototipo_principal.png
  docs/bocetos_interfez/a_prototipo_producto.png
Labels: documentation

#85 Uo271411 revision1
  docs/01_introduction_and_goals.adoc
  docs/11_technical_risks.adoc
  docs/bocetos_interfez/Boceto_Login.PNG
  docs/bocetos_interfez/Boceto_PrincipalYCarrito.PNG
  docs/images/DiagramaCalidad.png
  docs/images/DiagramaEnvio.png
Labels: documentation, review

#91 Version inicial backend para productos /home
  package-lock.json
  package.json
  restapi/api.ts
  restapi/controllers/ProductController.ts
  restapi/models/Product.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/routes/ProductRoutes.ts
  restapi/server.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/shared/shareddtypes.ts
Labels: implementación

#95 Vista de detallles terminada
  webapp/src/App.tsx
  webapp/src/components/Details.tsx
  webapp/src/components/LeftDetails.tsx
  webapp/src/components/List.tsx
  webapp/src/components/Nav.tsx
  webapp/src/components/RightDetails.tsx
  webapp/src/components/Shoes.tsx
  webapp/src/components/TableSizes.tsx
Labels: implementación

#101 Modificado estilo de diagramas y descirpción del sistema
  docs/01_introduction_and_goals.adoc
  docs/images/DiagramaCalidad.png
  docs/images/DiagramaEnvio.png
Labels: documentation, fixes

#107 Fixeado acceso a productos por medio de array
  restapi/api.ts
  restapi/server.ts
  restapi/shared/shareddtypes.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Home/Home.tsx
  webapp/src/components/Home/Shoes.tsx
  webapp/src/shared/shareddtypes.ts
Labels: bug, fixes, implementación

#108 Conectado a mongodb utilizando moongoose
  package-lock.json
  package.json
  restapi/.dockerignore
  restapi/Dockerfile
  restapi/api.ts
  restapi/controllers/ProductController.ts
  restapi/models/Product.ts
  restapi/models/productModel.ts
  restapi/package.json
  restapi/routes/ProductRoutes.ts
  restapi/server.ts
  restapi/shared/shareddtypes.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tsconfig.json
Labels: implementación

#110 Cabecera cors añadida
  restapi/server.ts
Labels: implementación

#113 Variable de entorno para la conexión a la DB.
  restapi/server.ts
Labels: implementación

#116 Búsqueda de los colores disponibles de un producto (según su referencia)
  restapi/rutas/productoRutas.ts
Labels: implementación

#120 Limpiando ficheros no utilizados de repositorio restapi
  restapi/README.md
  restapi/README_es.md
  restapi/monitoring/grafana/provisioning/dashboards/dashboard.yml
  restapi/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  restapi/monitoring/grafana/provisioning/datasources/datasource.yml
  restapi/monitoring/prometheus/prometheus.yml
Labels: implementación

#122 extraida funcion a modulo consultarREST.ts
  restapi/rutas/consultarREST.ts
  restapi/rutas/productoRutas.ts
Labels: implementación

#124 Se incorporan variables de entorno API_REST_PORT y API_REST_URL_BASE
  restapi/.env
  restapi/modelos/fotoModelo.ts
  restapi/rutas/productoRutas.ts
  restapi/server.ts
Labels: implementación

#127 Se añaden tallas a mongoDB. Se añaden operaciones a api rest
  restapi/modelos/productoModelo.ts
  restapi/modelos/tallaModelo.ts
  restapi/rutas/productoRutas.ts
  restapi/rutas/tallaRutas.ts
  restapi/server.ts
Labels: implementación

#130 Añadidas funciones para recuperar fotos de los productos en rest
  restapi/rutas/fotoRutas.ts
  restapi/rutas/productoRutas.ts
  restapi/rutas/tallaRutas.ts
Labels: implementación

#131 Ultimas modificaciones para la entrega del prototipo
  restapi/.env
  restapi/README.md
  restapi/README_es.md
  restapi/modelos/fotoModelo.ts
  restapi/modelos/productoModelo.ts
  restapi/modelos/tallaModelo.ts
  restapi/monitoring/grafana/provisioning/dashboards/dashboard.yml
  restapi/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json
  restapi/monitoring/grafana/provisioning/datasources/datasource.yml
  restapi/monitoring/prometheus/prometheus.yml
  restapi/rutas/consultarREST.ts
  restapi/rutas/fotoRutas.ts
  restapi/rutas/productoRutas.ts
  restapi/rutas/tallaRutas.ts
  restapi/server.ts
Labels: information

#151 Vista detalles: enlazado front con back end
  restapi/package-lock.json
  restapi/package.json
  restapi/rutas/productoRutas.ts
  webapp/src/api/api.ts
  webapp/src/components/Details/Details.tsx
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Home/Shoes.tsx
  webapp/src/shared/shareddtypes.ts
Labels: implementación

#156 Uo277876 actualizar doc entrega3
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/07_deployment_view.adoc
  docs/10_quality_scenarios.adoc
  docs/images/DiagramaDespliegue.png
Labels: documentation
