Repository Arquisoft/dede_es3a, pull requests merged in 2022-05, with the labels that each got.

#249 Test restapi arreglados + añadidos
  restapi/api.ts
  restapi/rutas/pedidoRutas.ts
  restapi/tests/api.test.tsx
  restapi/tests/jest.config.ts
  restapi/tests/servidor_test.tsx
Labels: bug, implementación, tests

#250 Arreglados test + code smells
  restapi/tests/api.test.tsx
  restapi/tests/servidor_test.tsx
  webapp/src/components/Details/LeftDetails.tsx
  webapp/src/test/Cart/CartButtons.test.tsx
  webapp/src/test/Details/LeftDetails.test.tsx
Labels: bug, tests

#252 Hotfix: redireccion url
  webapp/src/components/Login/FormLogIn.tsx
Labels: bug, fixes, backend

#257 Quitado menu de nav + correccion test
  restapi/tests/api.test.tsx
  webapp/src/components/Fragments/Nav.tsx
Labels: implementación, Frontend, tests

#260 Corrigiendo errores menores
  restapi/server.ts
  restapi/tests/api.test.tsx
  restapi/tests/servidor_test.tsx
  webapp/jest.config.ts
  webapp/package.json
  webapp/src/test/Developers/Us.test.tsx
  webapp/src/test/Home/Shoes.test.tsx
Labels: bug, tests

#262 arreglando bugs
  docs/bocetos_interfez/BocetoCarrito.html
  docs/bocetos_interfez/BocetoCarrito.png
  docs/bocetos_interfez/BocetoDetalleProducto.html
  docs/bocetos_interfez/BocetoDetalleProducto.png
  docs/bocetos_interfez/BocetoPaginaPrincipal.png
  docs/bocetos_interfez/BocetoPáginaPrincipal.html
  restapi/api.ts
  restapi/rutas/productoRutas.ts
  restapi/rutas/usuarioRutas.ts
  restapi/server.ts
  webapp/src/components/Requests/ListRequests.tsx
Labels: bug

#263 Actualizando doc
  README.md
  docs/07_deployment_view.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/DiagramaDespliegue.png
Labels: documentation

#265 test añadido
  webapp/src/test/Login/ErrorPod.test.tsx
Labels: tests

#266 Correcciones
  README.md
  docs/07_deployment_view.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/bocetos_interfez/BocetoCarrito.html
  docs/bocetos_interfez/BocetoCarrito.png
  docs/bocetos_interfez/BocetoDetalleProducto.html
  docs/bocetos_interfez/BocetoDetalleProducto.png
  docs/bocetos_interfez/BocetoPaginaPrincipal.png
  docs/bocetos_interfez/BocetoPáginaPrincipal.html
  docs/images/DiagramaDespliegue.png
  restapi/api.ts
  restapi/rutas/productoRutas.ts
  restapi/rutas/usuarioRutas.ts
  restapi/server.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/Login/ErrorPod.tsx
  webapp/src/components/Login/FormLogIn.tsx
  webapp/src/components/Login/ProfileViewer.tsx
  webapp/src/components/POD/GetAddressPod.tsx
  webapp/src/components/Requests/ListRequests.tsx
  webapp/src/test/Login/ErrorPod.test.tsx
Labels: bug, tests

#267 E2e
  .github/workflows/asw2122.yml
  webapp/e2e/features/Register.feature
  webapp/e2e/features/get-products.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/GetProduct.steps.ts
  webapp/e2e/steps/Register.steps.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/package.json
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Login/Register.tsx
Labels: tests

#270 readme
  README.md
  docs/images/logo.png
Labels: documentation

#271 readme rechulon
  README.md
  docs/images/logo.png
Labels: documentation

#272 doc review
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/08-Crosscutting-Concepts-Structure-EN.png
  docs/images/DiagramaDespliegue.png
  docs/images/DiagramaER.png
  docs/images/UmlDiagram.png
Labels: documentation

#273 Develop
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/08-Crosscutting-Concepts-Structure-EN.png
  docs/images/DiagramaDespliegue.png
  docs/images/DiagramaER.png
  docs/images/UmlDiagram.png
Labels: documentation

#274 arreglando problema ER
  docs/08_concepts.adoc
Labels: documentation

#275 Documentacion
  docs/08_concepts.adoc
Labels: documentation

#279 Hotfix vista pedidos y registro.
  webapp/src/components/Login/LoginUsrPsswd.tsx
  webapp/src/components/Login/Register.tsx
  webapp/src/components/Requests/ListRequests.tsx
  webapp/src/shared/shareddtypes.ts
Labels: bug, fixes, backend

#280 Cambios en funcionalidad tras la presentación
  webapp/src/components/Login/LoginUsrPsswd.tsx
  webapp/src/components/Login/Register.tsx
  webapp/src/components/Requests/ListRequests.tsx
  webapp/src/shared/shareddtypes.ts
Labels: review
