Repository Arquisoft/dede_es3a, pull requests merged in 2022-04, with the labels that each got.

#159 Reañadido login
  webapp/src/components/Login/Login.tsx
Labels: implementación, Frontend

#160 Primera version POD
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/Fragments/Nav.tsx
  webapp/src/components/Login/FormLogIn.tsx
  webapp/src/components/Login/Login.tsx
  webapp/src/components/Login/Login_v2.tsx
  webapp/src/components/Requests/Requests.tsx
Labels: implementación, Frontend

#163 Uo271447 login+pod
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Login/FormLogIn.tsx
  webapp/src/components/Login/Login.tsx
  webapp/src/components/Login/Login_v2.tsx
  webapp/src/components/Login/ProfileViewer.tsx
Labels: implementación

#165 Uo270149 monitoring
  package-lock.json
  package.json
  restapi/monitorizacion/grafana/provisioning/dashboard/dashboard.yml
  restapi/monitorizacion/grafana/provisioning/dashboard/example-service-dashboard.json
  restapi/monitorizacion/grafana/provisioning/datasources/datasources.yml
  restapi/monitorizacion/prometheus/prometheus.yml
Labels: implementación

#166 Creación de flujo de trabajo despliegueDevelop.yml
  restapi/Dockerfile
Labels: implementación

#168 LogIn correcto
  webapp/src/App.tsx
  webapp/src/components/Fragments/Nav.tsx
  webapp/src/components/Login/FormLogIn.tsx
  webapp/src/components/Login/Login.tsx
  webapp/src/components/Login/Login_v2.tsx
  webapp/src/components/Login/ProfileViewer.tsx
Labels: implementación, Frontend

#171 Carrito backend
  webapp/src/components/Cart/CartButons.tsx
  webapp/src/components/Cart/ShoesCart.tsx
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Home/Home.tsx
Labels: implementación

#170 Uo270149 tests
  restapi/api.ts
  restapi/modelos/productoModelo.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tests/servidor.tests.ts
Labels: implementación

#173 Hotfix: eliminar de carrito
  restapi/modelos/productoModelo.ts
  restapi/rutas/productoRutas.ts
  webapp/src/components/Cart/ShoesCart.tsx
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/shared/shareddtypes.ts
Labels: bug, fixes, implementación

#174 Uo68216 pruebas despliegue
  .github/workflows/despliegueDevelop.yml
  .github/workflows/heroku.yml
  docs/Pasos para actualizar la documentación.docx
  docs/~$sos para actualizar la documentación.docx
  restapi/.dockerignore
  restapi/.env
  restapi/Dockerfile
  restapi/rutas/productoRutas.ts
  restapi/server.ts
  webapp/Dockerfile
  webapp/package.json
  webapp/server.ts
  webapp/src/api/api.ts
Labels: implementación

#177 Backend Carrito
  restapi/modelos/productoModelo.ts
  webapp/src/components/Cart/ShoesCart.tsx
  webapp/src/components/Details/RightDetails.tsx
Labels: fixes, implementación

#189 Comando que falta
  README.md
  restapi/package.json
Labels: bug, fixes

#190 Hotfix: declaracion de algunas variables
  restapi/modelos/fotoModelo.ts
  restapi/modelos/productoModelo.ts
  restapi/modelos/tallaModelo.ts
  restapi/rutas/productoRutas.ts
  restapi/server.ts
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/Details/Details.tsx
  webapp/src/components/Home/Shoes.tsx
Labels: fixes, implementación

#193 añadiendo usuario en session(borrar sin deleteUsr)
  webapp/src/api/api.ts
  webapp/src/components/Cart/ShoesCart.tsx
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Fragments/Nav.tsx
  webapp/src/components/Login/LoginUsrPsswd.tsx
  webapp/src/components/Login/Register.tsx
  webapp/src/shared/shareddtypes.ts
Labels: implementación

#194 Incluidas fotos y tallas dentro de producto en el esquema de la BBDD
  restapi/modelos/productoModelo.ts
  restapi/rutas/productoRutas.ts
Labels: implementación

#198 Login backend
  restapi/api.ts
  restapi/modelos/usuarioModelo.ts
  restapi/rutas/productoRutas.ts
  restapi/rutas/usuarioRutas.ts
  restapi/server.ts
  webapp/src/api/api.ts
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Fragments/Nav.tsx
  webapp/src/components/Home/List.tsx
  webapp/src/components/Home/Shoes.tsx
  webapp/src/components/Login/LoginUsrPsswd.tsx
  webapp/src/shared/shareddtypes.ts
Labels: implementación, backend

#208 Extraida direccion del POD correctamente
  webapp/src/components/Login/ProfileViewer.tsx
  webapp/src/components/POD/GetAddressPod.tsx
Labels: implementación

#210 Registro de usuario
  restapi/api.ts
  restapi/modelos/usuarioModelo.ts
  restapi/rutas/usuarioRutas.ts
  webapp/src/api/api.ts
  webapp/src/components/Login/Register.tsx
Labels: implementación, backend

#218 v1 test webapp
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/Cart/Cart.tsx
  webapp/src/components/Details/Details.tsx
  webapp/src/components/Home/Home.tsx
  webapp/src/components/Home/Shoes.tsx
  webapp/src/components/Login/LoginUsrPsswd.tsx
  webapp/src/components/Login/Register.tsx
  webapp/src/components/Requests/Requests.tsx
  webapp/src/shared/shareddtypes.ts
  webapp/src/test/Cart.test.tsx
  webapp/src/test/Footer.test.tsx
  webapp/src/test/Home.test.tsx
  webapp/src/test/LeftDetails.test.tsx
  webapp/src/test/LoginUsrPsswd.test.tsx
  webapp/src/test/Register.test.tsx
  webapp/src/test/RightDetails.test.tsx
Labels: implementación, Frontend, tests

#220 Quitados nav del pod
  webapp/src/components/Login/FormLogIn.tsx
  webapp/src/components/Login/ProfileViewer.tsx
Labels: bug, implementación

#222 Arreglados imports
  restapi/modelos/productoModelo.ts
  restapi/rutas/productoRutas.ts
  webapp/src/shared/shareddtypes.ts
  webapp/src/test/Cart.test.tsx
  webapp/src/test/Home.test.tsx
  webapp/src/test/RightDetails.test.tsx
Labels: bug, implementación

#227 Añadidos nuevos test y vista de About us
  webapp/src/App.tsx
  webapp/src/components/Cart/CartButons.tsx
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Developers/Us.tsx
  webapp/src/components/Fragments/Nav.tsx
  webapp/src/components/Login/FormLogIn.tsx
  webapp/src/components/Login/Register.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/shared/shareddtypes.ts
  webapp/src/test/Cart/CartButtons.test.tsx
  webapp/src/test/Cart/ShoesCart.test.tsx
  webapp/src/test/Details/LeftDetails.test.tsx
  webapp/src/test/Details/RightDetails.test.tsx
  webapp/src/test/Details/TablesSizes.test.tsx
  webapp/src/test/Fragments/Footer.test.tsx
  webapp/src/test/Fragments/Nav.test.tsx
  webapp/src/test/Home/Home.test.tsx
  webapp/src/test/Home/List.test.tsx
  webapp/src/test/LeftDetails.test.tsx
  webapp/src/test/Login/FormLogIn.test.tsx
  webapp/src/test/Login/LoginUsrPsswd.test.tsx
  webapp/src/test/Login/Provider.test.tsx
  webapp/src/test/Login/Register.test.tsx
  webapp/src/test/Requests/ListRequest.test.tsx
  webapp/src/test/RightDetails.test.tsx
  webapp/src/test/Us.test.tsx/Us.test.tsx
Labels: implementación, Frontend, tests

#232 Arreglo de tests
  restapi/server.ts
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Fragments/Nav.tsx
  webapp/src/test/Details/RightDetails.test.tsx
  webapp/src/test/Fragments/Nav.test.tsx
  webapp/src/test/Login/LoginUsrPsswd.test.tsx
  webapp/src/test/Login/Provider.test.tsx
Labels: tests

#238 Tests
  webapp/src/App.tsx
  webapp/src/components/Cart/Cart.tsx
  webapp/src/components/Cart/CartButons.tsx
  webapp/src/components/Cart/ShoesCart.tsx
  webapp/src/components/Fragments/Nav.tsx
  webapp/src/components/Home/Home.tsx
  webapp/src/components/Requests/ListRequests.tsx
  webapp/src/components/Requests/Requests.tsx
  webapp/src/test/Cart/CartButtons.test.tsx
  webapp/src/test/Cart/ShoesCart.test.tsx
  webapp/src/test/Home/Home.test.tsx
  webapp/src/test/Login/Register.test.tsx
  webapp/src/test/Requests/ListRequest.test.tsx
Labels: implementación, tests

#239 Mas tests
  webapp/src/components/Cart/Cart.tsx
  webapp/src/components/Details/RightDetails.tsx
  webapp/src/components/Login/LoginUsrPsswd.tsx
  webapp/src/components/Login/Register.tsx
  webapp/src/components/Requests/ListRequests.tsx
  webapp/src/test/App.test.tsx
  webapp/src/test/Cart/Cart.test.tsx
  webapp/src/test/Details/Details.test.tsx
  webapp/src/test/Details/RightDetails.test.tsx
  webapp/src/test/Home/Home.test.tsx
  webapp/src/test/Home/Shoes.test.tsx
  webapp/src/test/Login/Login.test.tsx
  webapp/src/test/Login/LoginUsrPsswd.test.tsx
  webapp/src/test/Login/Profiler.test.tsx
  webapp/src/test/Login/Register.test.tsx
Labels: implementación, tests

#243 testrestapi
  restapi/README.md
  restapi/api.ts
  restapi/modelos/pedidoModelo.ts
  restapi/modelos/usuarioModelo.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/rutas/pedidoRutas.ts
  restapi/tests/api.test.tsx
  restapi/tests/jest.config.ts
  restapi/tests/servidor.tests.ts
  restapi/tests/servidor_test.tsx
Labels: backend, tests

#247 Hotfix: carrito
  .github/workflows/heroku_copy.yml
  docs/~$sos para actualizar la documentación.docx
  restapi/.env
  restapi/server.ts
  webapp/server.ts
  webapp/src/api/api.ts
  webapp/src/components/Cart/ShoesCart.tsx
  webapp/src/components/Login/FormLogIn.tsx
  webapp/src/components/Login/LoginUsrPsswd.tsx
Labels: bug, fixes, implementación, backend
