Repository Arquisoft/dede_es3a, pull requests merged in 2022-02, with the labels that each got.

#20 Uo68216 modificar doc
  docs/Documentacion2.txt
  docs/DocumentacionBorrador1
  docs/README.md
  docs/README_en.md
  docs/README_es.md
  docs/index.adoc
  docs/package-lock.json
Labels: documentation

#21 Prueba actualización de la documentación
  docs/index.adoc
  docs/package-lock.json
Labels: documentation

#22 Pasos para modificar la documentación
  docs/Pasos para actualizar la documentación.docx
Labels: documentation

#31 modificados a español títulos de la documentación
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
Labels: documentation

#34 Documentación doc10
  docs/10_quality_scenarios.adoc
  docs/images/DiagramaCalidad.png
Labels: documentation

#33 Se añade diagrama de contexto de negocio y explicación
  docs/images/03_diagramaContextoNegocio.png
Labels: documentation

#35 Documentación doc11 + diagrama de secuencia (envío)
  docs/11_technical_risks.adoc
  docs/images/DiagramaEnvio.png
Labels: documentation

#38 Añadido diagrama de secuencia para el cálculo de los gastos de envío
  docs/06_runtime_view.adoc
  docs/images/06_diagramaSecuenciaEnvio.png
Labels: documentation

#39 Añadidos términos al glosario
  docs/12_glossary.adoc
Labels: documentation

#43 Corregido formato puntos 10 y 11
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
Labels: documentation

#44 Develop
  README.md
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/03_diagramaContextoNegocio.png
  docs/images/05_diagramaDetalleNivel1.png
  docs/images/05_diagramaDetalleNivel2.png
  docs/images/05_diagramaGeneral.png
  docs/images/06_diagramaSecuenciaEnvio.png
  docs/images/DiagramaCalidad.png
  docs/images/DiagramaCompra.png
  docs/images/DiagramaDespliegue.png
  docs/images/DiagramaER.png
  docs/images/DiagramaEnvio.png
  docs/images/DiagramaLogin.JPG
  docs/images/cssOptimization.png
  docs/images/git.png
  docs/images/react.png
Labels: documentation

#74 Bocetos iniciales de la interfaz de usuario.
  docs/bocetos_interfez/BocetoCarrito.html
  docs/bocetos_interfez/BocetoDetalleProducto.html
  docs/bocetos_interfez/BocetoPáginaPrincipal.html
Labels: implementación

#72 Modificado usuario por cliente en los diagramas
  docs/images/03_diagramaContextoNegocio.png
  docs/images/05_diagramaDetalleNivel1.png
  docs/images/05_diagramaDetalleNivel2.png
  docs/images/05_diagramaGeneral.png
  docs/images/06_diagramaSecuenciaEnvio.png
Labels: documentation, fixes

#73 Modificado usuario por cliente. (Closes #64)
  docs/03_system_scope_and_context.adoc
Labels: documentation, fixes

#71 Correcciones puntos 2 y 7
  docs/02_architecture_constraints.adoc
  docs/07_deployment_view.adoc
  docs/12_glossary.adoc
  docs/images/DiagramaDespliegue.png
Labels: documentation, fixes

#75 Uo271411 revision1
  docs/01_introduction_and_goals.adoc
  docs/11_technical_risks.adoc
  docs/images/DiagramaCalidad.png
  docs/images/DiagramaCalidad.txt
  docs/images/DiagramaEnvio.png
  docs/images/DiagramaEnvio.txt
Labels: documentation, review

#77 Revert "Uo271411 revision1"
  docs/01_introduction_and_goals.adoc
  docs/11_technical_risks.adoc
  docs/images/DiagramaCalidad.png
  docs/images/DiagramaCalidad.txt
  docs/images/DiagramaEnvio.png
  docs/images/DiagramaEnvio.txt
Labels: documentation, fixes, review
